/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dailyarticle_utils_Jstr */

#ifndef _Included_com_example_dailyarticle_utils_Jstr
#define _Included_com_example_dailyarticle_utils_Jstr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dailyarticle_utils_Jstr
 * Method:    getJniString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dailyarticle_utils_Jstr_getJniString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
